### ISSUE TITLE
DIO request

### ISSUE THREAD

**Issue by nwaobasianthony** [SMotlaq/LoRa_third#2]
Does the library now support receive on interrupt now?

Thank you for your great work

**Comment by SMotlaq** [comment]
Hi my friend, yes you can get EXTI from DIO0 pin. But the LoRa_transmit function includes a HAL_Delay(1). So you can't use LoRa_transmit in your interrupt routine. Unless you replace the HAL_Delay(1) with a timer-based delay procedure.
Use the LoRa_init in the DIO branch.

**Comment by SMotlaq** [comment]
> 
> 
> Does the library now support receive on interrupt now?
> 
> Thank you for your great work

OK?
