### ISSUE TITLE
Hello!Can it be implemented in FreeRTOS？

### ISSUE THREAD

**Issue by ssg0412** [SMotlaq/LoRa_third#4]

**Comment by SMotlaq** [comment]
I'm so sorry because I don't know :((
I haven't worked with FreeRTOS yet.

**Comment by edilandrade** [comment]
Hello, thank you very much for sharing this lib, I implemented it and found some problem in receiving packets, when decreasing the delay in less than 300 ms starts to lose information to be received, would you have any solution?

**Comment by SMotlaq** [comment]
> 
> 
> Hello, thank you very much for sharing this lib, I implemented it and found some problem in receiving packets, when decreasing the delay in less than 300 ms starts to lose information to be received, would you have any solution?

How do you check the packets? Do you use Keil debugger? or what?

**Comment by edilandrade** [comment]
Estou usando o STMCubeIDE.

**Comment by edilandrade** [comment]
Na imagem mostro a recepção dos pacotes em uma leitura de 800ms ainda perde alguns pacotes. 

![image](https://user-images.githubusercontent.com/70067010/125071686-02b10480-e090-11eb-9633-a13dd09979fe.png)

**Comment by edilandrade** [comment]
a cada intervalo de tempo verifico a recepção 
caso deixe no loop diretamente o mesmo não funciona.

![image](https://user-images.githubusercontent.com/70067010/125072462-03966600-e091-11eb-88a4-21557c9fe3b3.png)

**Comment by SMotlaq** [comment]
Dude ENGLISH please :))

**Comment by edilandrade** [comment]
I am using STMCubeIDE.

**Comment by edilandrade** [comment]
at each time interval, reception is verified.
if you leave it in the loop directly, it doesn't work.

![image](https://user-images.githubusercontent.com/70067010/125088418-c38cae80-e0a3-11eb-8c7d-6e11c40d05df.png)

**Comment by edilandrade** [comment]
In the image I show the reception of packets at a reading of 800ms still lose some packets.

![image](https://user-images.githubusercontent.com/70067010/125088610-f6cf3d80-e0a3-11eb-9289-dde169444e21.png)

**Comment by edilandrade** [comment]
at every interval of time I check the reception
if you leave it in the loop directly, it doesn't work.

![image](https://user-images.githubusercontent.com/70067010/125088708-11a1b200-e0a4-11eb-8678-37168f09c97c.png)

**Comment by SMotlaq** [comment]
How fast is the transmitter?

**Comment by edilandrade** [comment]
It's transmitting at 3000ms

![image](https://user-images.githubusercontent.com/70067010/125193348-56ebee00-e222-11eb-9203-e65ae60e1e4f.png)

**Comment by SMotlaq** [comment]
Use DIO0 pin for receiver side. In EXTI callback use the LoRa_receive() and test it again.

**Comment by edilandrade** [comment]
thank you very much, it worked using callback working perfectly.

**Comment by SMotlaq** [comment]
Nice :)
Good luck ✌🏻✌🏻
