### ISSUE TITLE
STM32F407G-DISC1

### ISSUE THREAD

**Issue by SalihSalurr** [SMotlaq/LoRa_third#6]
Hello,

I have STM32F407G-DISC1 board and LoRa E32 433T20D.  I want to communicate LoRa with F407. Is this library work with F407. Has anyone tried? 

Thank you.

**Comment by SMotlaq** [comment]
Hi!
This library works on F407, but doesn't support your LoRa module. E32-433T20D has UART for communication, while Ra-02 uses SPI.

**Comment by SalihSalurr** [comment]
ohh, It's true, Thank you.

**Comment by SMotlaq** [comment]
🌹🙏🏻
