### ISSUE TITLE
LoRa cannot init

### ISSUE THREAD

**Issue by pingkung** [SMotlaq/LoRa_third#7]
Hi There,

I am trying to use your LoRa library for NUCLEO-G431KB and I always got the ERROR 404.
I checked all the wiring which are correct.

Any suggestion? 

Thanks in advance

**Comment by SMotlaq** [comment]
Hi!
Please send me your project. I will check it asap.
pilot.motlaq@gmail.com

**Comment by pingkung** [comment]
> Hi! Please send me your project. I will check it asap. [pilot.motlaq@gmail.com](mailto:pilot.motlaq@gmail.com)

The project was sent. Thanks for your reply.
