### ISSUE TITLE
what is LEVEL1_Pin LEVEL2_Pin LEVEL3_Pin LEVEL4_Pin

### ISSUE THREAD

**Issue by wangchaoHZ** [SMotlaq/LoRa_third#9]
I don't know the meaning of LEVEL1_Pin LEVEL2_Pin LEVEL3_Pin LEVEL4_Pin pins. Can you help me explain them clearly

**Comment by SMotlaq** [comment]
Where are they?

**Comment by wangchaoHZ** [comment]
> Where are they?

Thank you for reply, In this function  "static void MX_GPIO_Init(void)" in main.c file

**Comment by SMotlaq** [comment]
I connected 4 LEDs to these pins to represent the signal strength using LoRa_getRSSI function. But I forgot to delete them :)
You can ignore them.

**Comment by wangchaoHZ** [comment]
> I connected 4 LEDs to these pins to represent the signal strength using LoRa_getRSSI function. But I forgot to delete them :) You can ignore them.

thank you I've got it up and running.
